import numpy as np

In [2]:
import numpy as np

In [3]:
myarray=np.linspace(0,10,101) #0 ile 10 arasında eşit aralıklı 101 sayı üretiyor

In [4]:
# a dice is rolled many times and results saved to an array that called dice_rolls.
#how many integers in dice rolled greater than 2

In [5]:
dice_rolls = np.random.randint(1,7,1000)

In [6]:
total_rolls_over_2=len(dice_rolls[dice_rolls>2])

In [7]:
# NUMPY OPERATİONS

In [8]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr.sum()

45

In [11]:
arr.std()

2.8722813232690143

In [12]:
arr2d = np.arange(0,25).reshape(5,5)

In [13]:
arr2d.sum()

300

In [15]:
arr2d.sum(axis=0) # sum of rows

array([50, 55, 60, 65, 70])

In [16]:
arr2d.sum(axis=1) # sum of columns

array([ 10,  35,  60,  85, 110])

In [19]:
#create an array of 10 zeros
arrzero = np.zeros(10)

In [20]:
arrzero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
#create an array of 10 fives
arrfive=np.ones(10)*5

In [22]:
arrfive

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
#create an array of all the even integers from 10 to 50
arreven = np.arange(10,51,2)
arreven

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [24]:
#generate a random number between 0 and 1
np.random.rand(1)

array([0.31550603])

In [25]:
#generate a 25 random number sampled from a std normal dist.
np.random.randn(25)

array([ 0.78418541,  0.78500745,  1.93760839,  0.94721427,  0.85193644,
        0.36040023, -0.14277957, -0.4936257 , -1.18127747, -0.19453924,
        0.68600718, -1.26016772, -0.3432674 ,  0.49380963, -1.02313975,
        0.72355114,  0.25612054,  1.03897623, -0.48491228,  0.99399808,
       -2.02415519,  0.7314455 , -1.8470257 , -0.45348715, -0.11986146])